added spack_config and spack_package data
ACCESS-NRI/build-cd pull request #104
Opened 2024-07-02 00:54 UTC by utkarshgupta95

resolves ACCESS-NRI/experiment-metadb#15

2024-07-02 00:59 UTC, CodeGat commented
Thanks @utkarshgupta95 - I might add some commits as well so the workflow works

2024-07-03 03:41 UTC, CodeGat approved these changes
The stuff that @utkarshgupta95 has done looks good. I'll need someone to verify that my stuff is good, as well.

2024-07-04 02:11 UTC, aidanheerdegen requested changes
Just a minor quibble about naming

2024-07-04 02:11 UTC, aidanheerdegen commented on scripts/generate-build-metadata.bash
> +      spack_package: $spack_packages_version,
```suggestion
      spack_packages: $spack_packages_version,
```
It's a small detail, but we should be consistent with the naming of `spack_packages`

2024-07-04 02:11 UTC, aidanheerdegen commented on tests/scripts/generate-build-metadata/valid/build_metadata.json
> +    "spack_package": "2023.11.23",
```suggestion
    "spack_packages": "2023.11.23",
```

2024-07-04 02:11 UTC, aidanheerdegen commented on tools/release_provenance/models.py
> +    spack_package = Column(String)
```suggestion
    spack_packages = Column(String)
```

2024-07-04 02:11 UTC, aidanheerdegen commented on tools/release_provenance/save_release.py
> +        model_build.spack_package = model_build_data["spack_package"]
```suggestion
        model_build.spack_packages = model_build_data["spack_packages"]
```

2024-07-04 02:11 UTC, aidanheerdegen commented on tools/release_provenance/test_release_data.json
> +      "spack_package": "0.20.3",
```suggestion
      "spack_packages": "0.20.3",
```

2024-07-04 02:58 UTC, utkarshgupta95 commented
@aidanheerdegen just to confirm `spack_packages` is not an array?

2024-07-05 05:28 UTC, aidanheerdegen approved these changes
Looks great, thanks!

2024-07-08 02:02 UTC, merged